# Form implementation generated from reading ui file 'list_dlg.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_list_dlg(object):
    def setupUi(self, list_dlg):
        list_dlg.setObjectName("list_dlg")
        list_dlg.resize(400, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(list_dlg.sizePolicy().hasHeightForWidth())
        list_dlg.setSizePolicy(sizePolicy)
        list_dlg.setMinimumSize(QtCore.QSize(0, 0))
        list_dlg.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.verticalLayout = QtWidgets.QVBoxLayout(list_dlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.text = QtWidgets.QTextEdit(list_dlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text.sizePolicy().hasHeightForWidth())
        self.text.setSizePolicy(sizePolicy)
        self.text.setAutoFillBackground(True)
        self.text.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.text.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.text.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.WidgetWidth)
        self.text.setReadOnly(True)
        self.text.setObjectName("text")
        self.verticalLayout.addWidget(self.text)
        self.buttonBox = QtWidgets.QDialogButtonBox(list_dlg)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(list_dlg)
        self.buttonBox.accepted.connect(list_dlg.accept) # type: ignore
        self.buttonBox.rejected.connect(list_dlg.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(list_dlg)

    def retranslateUi(self, list_dlg):
        _translate = QtCore.QCoreApplication.translate
        list_dlg.setWindowTitle(_translate("list_dlg", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    list_dlg = QtWidgets.QDialog()
    ui = Ui_list_dlg()
    ui.setupUi(list_dlg)
    list_dlg.show()
    sys.exit(app.exec())
