# Form implementation generated from reading ui file 'C:\usr\Code\Anki\addons\search-to-notes\src\py\enterdialog.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EnterDialog(object):
    def setupUi(self, EnterDialog):
        EnterDialog.setObjectName("EnterDialog")
        EnterDialog.resize(400, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(EnterDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.terms = QtWidgets.QPlainTextEdit(parent=EnterDialog)
        self.terms.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.terms.setObjectName("terms")
        self.verticalLayout.addWidget(self.terms)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=EnterDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(EnterDialog)
        self.buttonBox.accepted.connect(EnterDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(EnterDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(EnterDialog)

    def retranslateUi(self, EnterDialog):
        _translate = QtCore.QCoreApplication.translate
        EnterDialog.setWindowTitle(_translate("EnterDialog", "Enter/paste search terms"))
