# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enter_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_enter_dlg(object):
    def setupUi(self, enter_dlg):
        enter_dlg.setObjectName("enter_dlg")
        enter_dlg.resize(400, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(enter_dlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.terms = QtWidgets.QPlainTextEdit(enter_dlg)
        self.terms.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.terms.setObjectName("terms")
        self.verticalLayout.addWidget(self.terms)
        self.buttonBox = QtWidgets.QDialogButtonBox(enter_dlg)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(enter_dlg)
        self.buttonBox.accepted.connect(enter_dlg.accept)
        self.buttonBox.rejected.connect(enter_dlg.reject)
        QtCore.QMetaObject.connectSlotsByName(enter_dlg)

    def retranslateUi(self, enter_dlg):
        _translate = QtCore.QCoreApplication.translate
        enter_dlg.setWindowTitle(_translate("enter_dlg", "Enter/paste search terms"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    enter_dlg = QtWidgets.QDialog()
    ui = Ui_enter_dlg()
    ui.setupUi(enter_dlg)
    enter_dlg.show()
    sys.exit(app.exec_())
