# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\usr\Code\Anki\addons\search-to-notes\src\py\enterdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EnterDialog(object):
    def setupUi(self, EnterDialog):
        EnterDialog.setObjectName("EnterDialog")
        EnterDialog.resize(400, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(EnterDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.terms = QtWidgets.QPlainTextEdit(EnterDialog)
        self.terms.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.terms.setObjectName("terms")
        self.verticalLayout.addWidget(self.terms)
        self.buttonBox = QtWidgets.QDialogButtonBox(EnterDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(EnterDialog)
        self.buttonBox.accepted.connect(EnterDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(EnterDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(EnterDialog)

    def retranslateUi(self, EnterDialog):
        _translate = QtCore.QCoreApplication.translate
        EnterDialog.setWindowTitle(_translate("EnterDialog", "Enter/paste search terms"))
